### PR TITLE
Feature js

### PR DESCRIPTION
**Pull request by IjzerenHein**

### CODE REVIEW

**Comment by Qix-** [comment]
Any reason why Nan isn't being used?

**Comment by sccolbert** [comment]
> Any reason why Nan isn't being used?

Used for what?

**Comment by Qix-** [comment]
@sccolbert Nan abstracts the breaking API changes between Node versions.

**Comment by piksel** [comment]
This PR removes all python and C++ code, is this intentional?

**Comment by IjzerenHein** [comment]
This PR is for the `feature-js` branch, so yes.

This should however not be merged anymore. Kiwi.js has been moved to a separate repository here:
https://github.com/IjzerenHein/kiwi.js

**Comment by SauravMaheshkar** [comment]
If this PR isn't meant to be merged maybe we should just close it 🤷🏻‍♂️

CC: @IjzerenHein @MatthieuDartiailh

**Comment by MatthieuDartiailh** [comment]
Thanks for the note @Qix-

**Pull request closed without merging**
