### PR TITLE
Fixed binary operators for Constraint, Variable and Symbol class

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This is based on #4 but add the requested changes to Variable and Symbol.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
This should address your comments on #4. Anything else you would like to see before merging ?

**Comment by MatthieuDartiailh** [comment]
ping @sccolbert

**Comment by MatthieuDartiailh** [comment]
Ping @sccolbert

**Comment by MatthieuDartiailh** [comment]
This completes the work started in #4 as requested by @sccolbert. Will merge right after #22.

**Comment by sccolbert** [comment]
:+1: :shipit:

**Comment by MatthieuDartiailh** [comment]
I simply rebased on top of current master. Merging

**Pull request merged**
