### PR TITLE
Add C++ benchmark

### PR DESCRIPTION
**Pull request by SirLynix**
Hi!

As discussed in #89 here's a C++ benchmark of kiwi. It does the same thing as the Python benchmark, and I also added a benchmark of the solver building step.

Initially I was going to use a makefile for building this but it seems a bit overkill since there's only one file to build with a few options (I have to admit I'm not comfortable with makefile writing too).

I used [benchpress](https://github.com/cjgdev/benchpress), a header-only benchmark tool for C++11.

Here's the output on my machine:
```
$ ./build_and_run_bench.sh
building solver                            5000      374140 ns/op
suggest 400x600                         1000000        1244 ns/op
suggest 600x400                         1000000        1224 ns/op
suggest 800x1200                        1000000        1228 ns/op
suggest 1200x800                        1000000        1218 ns/op
suggest 400x800                         1000000        1234 ns/op
suggest 800x400                         1000000        1216 ns/op
./run_bench 17.279s
```

Bonus:
Here's the output with #89 applied
```
$ ./build_and_run_bench.sh
building solver                            5000      362501 ns/op
suggest 400x600                         1000000        1182 ns/op
suggest 600x400                         1000000        1155 ns/op
suggest 800x1200                        1000000        1169 ns/op
suggest 1200x800                        1000000        1177 ns/op
suggest 400x800                         1000000        1199 ns/op
suggest 800x400                         1000000        1190 ns/op
./run_bench 16.711
```

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@SirLynix can you have this run as part of the CIs ? As a new job ? I don't have a good place to store the results but at least running the benchmark would be nice.

Apart from that LGTM.

**Comment by Qix-** [comment]
Sorry to be picky, but I don't trust this benchmark framework - benchmarking is a bit more than "time this loop". Further, it's not been updated over a number of years, and the maintainer has suggested it's for beginners.

As much as I dislike recommending Google code, have you considered google's benchmarking library? It's, more or less, the defacto in the industry: https://github.com/google/benchmark

**Comment by SirLynix** [comment]
@MatthieuDartiailh Sure, but I'm not really familiar with this, I'll check how I can do that.
@Qix- You're right, google/benchmark would be better and I just saw it can be installed as part of the system, give me a few minutes and I'm reworking this.

**Comment by SirLynix** [comment]
Here you are
```
$ ./build_and_run_bench.sh
2020-09-10 11:25:43
Running ./run_bench
Run on (24 X 3800 MHz CPU s)
Load Average: 0.52, 0.58, 0.59
-----------------------------------------------------------------
Benchmark                       Time             CPU   Iterations
-----------------------------------------------------------------
building_solver            379559 ns       374930 ns         1792
suggest_value/400/600        1316 ns         1318 ns       497778
suggest_value/600/400        1312 ns         1287 ns       497778
suggest_value/800/1200       1308 ns         1311 ns       560000
suggest_value/1200/800       1306 ns         1311 ns       560000
suggest_value/400/800        1317 ns         1311 ns       560000
suggest_value/800/400        1310 ns         1318 ns       497778
```

with movement optimization:
```
$ ./build_and_run_bench.sh
2020-09-10 11:25:55
Running ./run_bench
Run on (24 X 3800 MHz CPU s)
Load Average: 0.52, 0.58, 0.59
-----------------------------------------------------------------
Benchmark                       Time             CPU   Iterations
-----------------------------------------------------------------
building_solver            373306 ns       376607 ns         1867
suggest_value/400/600        1181 ns         1172 ns       560000
suggest_value/600/400        1186 ns         1172 ns       560000
suggest_value/800/1200       1193 ns         1196 ns       640000
suggest_value/1200/800       1234 ns         1228 ns       560000
suggest_value/400/800        1194 ns         1172 ns       640000
suggest_value/800/400        1186 ns         1196 ns       640000
```

Of course I'm not performing this benchmark in perfect conditions (about 10% of CPU usage, using WSL1 to run this), I'll look about making an action running this.

**Comment by Qix-** [comment]
Please don't benchmark on WSL1. Its timing syscalls are unstable at best. Please run the benchmarks on native windows or a native linux installation.

**Comment by SirLynix** [comment]
Will do in about one hour or two.

**Comment by SirLynix** [comment]
Here are the results on my dedicated server (Ubuntu server 20.04):

```
lynix@ns382895:~/kiwi/benchmarks$ ./build_and_run_bench.sh
2020-09-10 14:07:43
Running ./run_bench
Run on (8 X 3800 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 256K (x4)
  L3 Unified 8192K (x1)
Load Average: 0.07, 0.05, 0.05
-----------------------------------------------------------------
Benchmark                       Time             CPU   Iterations
-----------------------------------------------------------------
building_solver            537400 ns       537429 ns         1294
suggest_value/400/600        1775 ns         1775 ns       387753
suggest_value/600/400        1759 ns         1759 ns       396156
suggest_value/800/1200       1761 ns         1761 ns       396850
suggest_value/1200/800       1765 ns         1765 ns       394433
suggest_value/400/800        1748 ns         1748 ns       390471
suggest_value/800/400        1755 ns         1755 ns       397721
```

with c++11-move merged:
```
lynix@ns382895:~/kiwi-move/benchmarks$ ./build_and_run_bench.sh
2020-09-10 14:08:06
Running ./run_bench
Run on (8 X 3800 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 256K (x4)
  L3 Unified 8192K (x1)
Load Average: 0.08, 0.06, 0.06
-----------------------------------------------------------------
Benchmark                       Time             CPU   Iterations
-----------------------------------------------------------------
building_solver            522964 ns       522981 ns         1334
suggest_value/400/600        1744 ns         1744 ns       400946
suggest_value/600/400        1775 ns         1775 ns       396587
suggest_value/800/1200       1740 ns         1740 ns       399110
suggest_value/1200/800       1750 ns         1750 ns       398541
suggest_value/400/800        1757 ns         1757 ns       400339
suggest_value/800/400        1750 ns         1750 ns       399852
```

It seems the performance boost, if existing, is marginal when it comes to suggest_value usage, which is kinda logical after rereading the code, since `suggestValue` doesn't use the constructors I changed.
However, building_solver does show an improvement related to movement.

**Review by Qix- — APPROVED** [review]
Looks good. Thanks for doing all that :) Sorry for being a source of friction ;)

**Comment by SirLynix** [comment]
Np problem, it's for the better.

Do you happen to have experience with GitHub actions? I don't understand why it's not finding the `benchmarks` directory.

**Comment by Qix-** [comment]
Add this as your first step:

```yaml
      - uses: actions/checkout@v2
```

**Comment by SirLynix** [comment]
> Github doesn't automatically pull the repository when an action runs.
Thank you! It did the trick.

> Maybe nanobench is better.
I don't know benchmarks tools and can't say about this, but it seems nanobench does print more information than google/benchmark indeed.

**Comment by Qix-** [comment]
Looks really nice, thanks for the rec @data-man.

**Comment by SirLynix** [comment]
I don't have the time to do this rn, but I will use it to replace google/benchmark then.

**Comment by SirLynix** [comment]
Here are the result with nanobench:

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          604,376.00 |            1,654.60 |    0.6% |      0.01 | `building solver`
|            1,974.42 |          506,478.71 |    0.2% |      0.00 | `suggest value 400x600`
|            1,967.73 |          508,200.51 |    0.2% |      0.00 | `suggest value 600x400`
|            1,967.10 |          508,362.56 |    0.2% |      0.00 | `suggest value 800x1200`
|            1,966.27 |          508,576.45 |    0.1% |      0.00 | `suggest value 1200x800`
|            1,966.60 |          508,491.81 |    0.1% |      0.00 | `suggest value 400x800`
|            1,965.45 |          508,788.16 |    0.1% |      0.00 | `suggest value 800x400`

with c++11-move merged:

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          600,539.00 |            1,665.17 |    0.6% |      0.01 | `building solver`
|            2,071.08 |          482,839.09 |    0.9% |      0.00 | `suggest value 400x600`
|            1,938.92 |          515,751.92 |    0.0% |      0.00 | `suggest value 600x400`
|            1,941.80 |          514,986.10 |    0.2% |      0.00 | `suggest value 800x1200`
|            1,917.58 |          521,489.72 |    0.1% |      0.00 | `suggest value 1200x800`
|            1,921.00 |          520,562.21 |    0.1% |      0.00 | `suggest value 400x800`
|            1,919.20 |          521,050.44 |    0.0% |      0.00 | `suggest value 800x400`

**Comment by SirLynix** [comment]
Okay this seems good now. I tried to use `pyperf system tune` to tune the system but it seems to no like VMs very much unfortunately.

**Comment by MatthieuDartiailh** [comment]
Thanks I will merge then.

**Pull request merged**
