### PR TITLE
3.13 support

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by QuLogic** [comment]
If dropping 3.7 support, you can also remove the `KIWI_DISABLE_FH4` flag, cf https://github.com/matplotlib/matplotlib/pull/28725

**Comment by neutrinoceros** [comment]
Hi ! I don't know if that was intented, but I see that the 1.4.6 release only has one wheel for cp313. Namely, `kiwisolver-1.4.6-cp313-cp313-win_arm64.whl`

**Comment by MatthieuDartiailh** [comment]
I just checked PyPI and I see much more than one. Can you re-check ?

**Comment by neutrinoceros** [comment]
FWIW, I'm still seeing just the one (looking at https://pypi.org/simple/kiwisolver/)
Could it be that I'm just served by an out-of-sync server ? I can just check again in an hour or so.

**Comment by QuLogic** [comment]
The build [here](https://github.com/nucleic/kiwi/actions/runs/10686725301/job/29623586765#step:4:89) shows only one 3.13 wheel being uploaded.

I think you may have run into the bug with `upload-artifact`/`download-artifact` that prompted their change to v4. To fix that, you would have to change uploading to use unique artifact names. See for example [the GH104 error on repo-review](https://learn.scientific-python.org/development/guides/repo-review/?repo=nucleic%2Fkiwi&branch=main), or [the update in Matplotlib](https://github.com/matplotlib/matplotlib/pull/27563/commits/26dfad29df673ccb19564c8b2e370e761ab341cd).

**Comment by neutrinoceros** [comment]
thank you !

**Pull request merged**
