### PR TITLE
Add ARM dll PATH to Windows ARM CIBW job

### PR DESCRIPTION
**Pull request by ksunden**
This is a follow up to #179 based on adang1345/delvewheel#44

I marked this as a draft as I'd prefer to get it tested prior to merge since I do not actually know for certain that it will work.

I can try to get it to run on my fork (may have to edit the workflow run conditions).

If you are interested, we do have machinery in MPL for running conditionally on a PR based on label presence.
I could try to add that, though may fall into the category of "too much for how often it is used"/"need to be extra careful about not triggering releases unintentionally".

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I just pushed something on main to test ARM and link against VC2014_1 also. I will let you know how it goes.

**Comment by MatthieuDartiailh** [comment]
Can you also remove the DISABLE_FH4 env var. If we bundle the dll there is no reason to use an old one.

**Comment by MatthieuDartiailh** [comment]
You can have a look at how pyzmq maintainer dealt with the path discovery issue at https://github.com/zeromq/pyzmq/pull/1951/files

**Comment by ksunden** [comment]
Okay, I think the version in now should work, at least for now...

Here is a successful fun (from before my last rebase which included your commit taking out the FH4 env var):


https://github.com/ksunden/kiwi/actions/runs/9813199691/job/27098741691#step:10:616


If you wish to adopt pyzmq's finding, I'll leave that to you. A cursory look at that PR looks like it is indeed just automating what I did, but did not read it closely. I left a comment with the `tree` command I used to get the numbers that were valid.

**Review by MatthieuDartiailh — APPROVED** [review]

**Pull request merged**
